### PR TITLE
Math Magicians: setup

### PR DESCRIPTION
**Pull request by developertariq**
Set up the environment and tools needed to develop a React application.

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @developertariq, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should use a professional documentations, kindly make sure to use the README provided by microverse

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mckent05 — APPROVED** [review]
Hi @developertariq, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
approved


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestion
**OPTIONAL** - Please ensure that all merge conflicts with the base branch are resolved 🙏 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mckent05** [comment]
> Hi @developertariq,
> 
> # STATUS: APPROVED ✔️ ✔️
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations and well done! 🎉 approved [ approved ](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif) [ ](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)
> 
> ## Highlights
> * All linter checks are passing ✔️ ✔️
> * Your PR is professional 👏 👏
> 
> ## Optional suggestion
> **OPTIONAL** - Please ensure that all merge conflicts with the base branch are resolved 🙏 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**I have approved your project in error, When I should have in fact invalidated it because you have used the wrong workflow for this milestone, please make sure you use Gitflow for this milestone and ensure the `dev` branch is your base branch**

**Comment by developertariq** [comment]
Hi @mckent05, 

Thanks for your suggestion, it's updated to the dev branch.

**Comment by developertariq** [comment]
Hello @mckent05, 

I have also resolved all conflicts before merging.

**Comment by mckent05** [comment]
> Hi @mckent05,
> 
> Thanks for your suggestion, it's updated to the dev branch.

Hello @developertariq, I am sorry for my initial mistake, but I would have to invalidate your project for that reason, Please open and submit a new PR for this milestone. I am sorry for any inconvenience on my end 🙏 🙏

**Pull request merged**
